import { Poppins } from "next/font/google";
import "./globals.css";

const pop = Poppins({ subsets: ["latin"],weight:["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata = {
  title: "SAC | SSIPMT",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/sac_logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="shortcut icon" href="/logo/sac_logo.svg" />
      <body className={pop.className}>{children}</body>
    </html>
  );
}
